ollama:
  baseUrl: ""

image:
  repository: shrihari7396
  tag: latest

secrets:
  apiGatewaySentinelSecretKey: ""
  apiGatewayJwtSecretKey: ""
  postgresUser: ""
  postgresPassword: ""

rolloutId: ""
