apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: {{ .Release.Namespace }}
data:
  KAFKA_NODE_ID: "1"
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-service.sentientgate.svc.cluster.local:9092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: sentientgate
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.7.1
          envFrom:
            - configMapRef:
                name: kafka-config
          ports:
            - name: broker
              containerPort: 9092
            - name: controller
              containerPort: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: sentientgate
spec:
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
  selector:
    app: kafka
