apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-server-config
  namespace: {{ .Release.Namespace }}
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka"
  GRPC_CLIENT_LOGGING_SERVICE_ADDRESS: "dns:///logging-service:9090"
  SERVER_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
  namespace: sentientgate
  labels:
    app: mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server
  template:
    metadata:
      annotations:
        sentientgate/release-id: {{ .Values.rolloutId | quote }}
      labels:
        app: mcp-server
    spec:
      containers:
        - name: mcp-server
          image: shrihari7396/mcp-server:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: mcp-server-config
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: sentientgate
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: mcp-server
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mcp-server-kafka-scaledobject
  namespace: sentientgate
spec:
  scaleTargetRef:
    name: mcp-server
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka-service.sentientgate.svc.cluster.local:9092
        consumerGroup: mcp-analysis-group
        topic: security-events
        lagThreshold: "10"
