apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SENTINEL_SECRET_KEY: {{ required "secrets.apiGatewaySentinelSecretKey is required" .Values.secrets.apiGatewaySentinelSecretKey | quote }}
  JWT_SECRET_KEY: {{ required "secrets.apiGatewayJwtSecretKey is required" .Values.secrets.apiGatewayJwtSecretKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ required "secrets.postgresUser is required" .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ required "secrets.postgresPassword is required" .Values.secrets.postgresPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: logging-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ required "secrets.postgresUser is required" .Values.secrets.postgresUser | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ required "secrets.postgresPassword is required" .Values.secrets.postgresPassword | quote }}
