apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: sentinel-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentinel-ui
  template:
    metadata:
      annotations:
        sentientgate/release-id: {{ .Values.rolloutId | quote }}
      labels:
        app: sentinel-ui
    spec:
      containers:
        - name: sentinel-ui
          image: shrihari7396/sentinel-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-ui
  namespace: sentientgate
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: sentinel-ui
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sentinel-ui-hpa
  namespace: sentientgate
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sentinel-ui
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
